---
- name: Perform a dist-upgrade (Debian Based Servers)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Remove useless packages from the cache (Debian Based Servers)
  apt:
    autoclean: yes
  when: ansible_os_family == 'Debian'

- name: Remove dependencies that are no longer required (Debian Based Servers)
  ansible.builtin.apt:
    autoremove: yes
  when: ansible_os_family == 'Debian'
